### PR TITLE
fix: don't panic if a bloom counter underflows

### LINKED ISSUE #3599: BUG: item is present in the bloom counter, but has a zero count
**Describe the bug**
Saw this log come up in roughly a dozen different mainnet stacks nodes which caused it to crash, all running 2.05.0.6.0. The nodes crashed around 5-7 times each before somehow getting past the bug.

Below are the logs, including a trace. Let me know if more information is needed!

```
stacks-blockchain {"msg":"stacks-node 2.05.0.6.0 (master:a71871a, release build, linux [x86_64])","level":"INFO","ts":"2023-03-02T16:57:38.869993759+00:00","thread":"main","line":82,"file":"testnet/stacks-node/src/main.rs"}
stacks-blockchain {"msg":"Loading config at path /app/config.toml","level":"INFO","ts":"2023-03-02T16:57:38.870136657+00:00","thread":"main","line":140,"file":"testnet/stacks-node/src/main.rs"}
stacks-blockchain {"msg":"Registering event observer at: mainnet-api-archive.mainnet-api-dr.svc.cluster.local:3700","level":"INFO","ts":"2023-03-02T16:57:38.881015310+00:00","thread":"main","line":963,"file":"testnet/stacks-node/src/event_dispatcher.rs"}
stacks-blockchain {"msg":"Migrating sortition DB to the latest schema version","level":"INFO","ts":"2023-03-02T16:57:38.911326058+00:00","thread":"main","line":970,"file":"src/chainstate/coordinator/mod.rs"}
stacks-blockchain {"msg":"Migrating chainstate DB to the latest schema version","level":"INFO","ts":"2023-03-02T16:57:38.912566387+00:00","thread":"main","line":974,"file":"src/chainstate/coordinator/mod.rs"}
stacks-blockchain {"msg":"Start syncing Bitcoin headers, feel free to grab a cup of coffee, this can take a while","level":"INFO","ts":"2023-03-02T16:57:38.915549284+00:00","thread":"main","line":374,"file":"testnet/stacks-node/src/run_loop/neon.rs"}
stacks-blockchain {"msg":"New canonical Bitcoin chain found! New tip is 00000000000000000001798f4ef4c881978f2ead703c8a61c35f1b923da75b13","level":"INFO","ts":"2023-03-02T16:57:39.060879202+00:00","thread":"main","line":716,"file":"src/burnchains/bitcoin/indexer.rs"}
stacks-blockchain {"msg":"Syncing Bitcoin blocks: 100.0% (778994 to 778995 out of 778994)","level":"INFO","ts":"2023-03-02T16:57:39.124840182+00:00","thread":"main","line":1314,"file":"src/burnchains/burnchain.rs"}
stacks-blockchain {"msg":"Will run as a Follower node","level":"INFO","ts":"2023-03-02T16:57:41.441227644+00:00","thread":"main","line":333,"file":"testnet/stacks-node/src/run_loop/neon.rs"}
stacks-blockchain {"msg":"Start serving prometheus metrics","level":"INFO","ts":"2023-03-02T16:57:41.453031731+00:00","thread":"prometheus","line":9,"file":"testnet/stacks-node/src/monitoring/mod.rs"}
stacks-blockchain {"msg":"Prometheus monitoring: server listening on http://0.0.0.0:9153","level":"INFO","ts":"2023-03-02T16:57:41.454293978+00:00","thread":"prometheus","line":21,"file":"testnet/stacks-node/src/monitoring/prometheus.rs"}
stacks-blockchain {"msg":"PoX recipient chosen","level":"INFO","ts":"2023-03-02T16:57:41.506967037+00:00","thread":"chains-coordinator-0.0.0.0:20443","line":1255,"file":"src/chainstate/burn/db/sortdb.rs","block_height":778995,"recipient":"3KmktaxrovGDQX5A1JAQp95NK8GdRVgy5j"}
stacks-blockchain {"msg":"PoX recipient chosen","level":"INFO","ts":"2023-03-02T16:57:41.507394259+00:00","thread":"chains-coordinator-0.0.0.0:20443","line":1255,"file":"src/chainstate/burn/db/sortdb.rs","block_height":778995,"recipient":"33WSGLeVoEpuZDjB54HKZ1y5YsERELoVNq"}
stacks-blockchain {"msg":"Will bootstrap from peers [03489ab16159c7b3825e6160d964be60058ace9b85269117d356cea7dbda34ba27@18000005+00000001://34.145.178.0:20444]","level":"INFO","ts":"2023-03-02T16:57:41.551799166+00:00","thread":"main","line":3628,"file":"testnet/stacks-node/src/neon_node.rs"}
stacks-blockchain {"msg":"Start HTTP server on: 0.0.0.0:20443","level":"INFO","ts":"2023-03-02T16:57:41.599020205+00:00","thread":"main","line":3919,"file":"testnet/stacks-node/src/neon_node.rs"}
stacks-blockchain {"msg":"Start P2P server on: 0.0.0.0:20444","level":"INFO","ts":"2023-03-02T16:57:41.599169815+00:00","thread":"main","line":3920,"file":"testnet/stacks-node/src/neon_node.rs"}
stacks-blockchain {"msg":"local.1://(bind=0.0.0.0:20444)(pub=None): failed to learn public IP: NoSuchNeighbor","level":"WARN","ts":"2023-03-02T16:57:42.358903581+00:00","thread":"p2p-(0.0.0.0:20444,0.0.0.0:20443)","line":2464,"file":"src/net/p2p.rs"}
stacks-blockchain {"msg":"Handle HTTPRequest","level":"INFO","ts":"2023-03-02T16:57:42.426501673+00:00","thread":"p2p-(0.0.0.0:20444,0.0.0.0:20443)","line":1635,"file":"src/net/http.rs","query":"","path":"/v2/info","peer_addr":"10.0.18.18:53665","verb":"GET"}
stacks-blockchain {"msg":"IP address changed from None to Some((00000000000000000000ffff0a001109, 20444))","level":"INFO","ts":"2023-03-02T16:57:42.619541218+00:00","thread":"p2p-(0.0.0.0:20444,0.0.0.0:20443)","line":2346,"file":"src/net/p2p.rs"}
stacks-blockchain {"msg":"ACCEPTED(778995) leader block commit df87f0d21504b905ab251901c24bbd74b13354b3bc26ec30137b97c26b52833a at 778995,94","level":"INFO","ts":"2023-03-02T16:57:43.387753990+00:00","thread":"chains-coordinator-0.0.0.0:20443","line":3814,"file":"src/chainstate/burn/db/sortdb.rs","apparent_sender":"1JMGT8rNTqZVQ8VzL34P61mucUtTyv35YP"}
stacks-blockchain {"msg":"ACCEPTED(778995) leader block commit ddc01f6522b51a872a7d1e272c7b5bca7433eb116cadbd809e6f124c7c5c9976 at 778995,311","level":"INFO","ts":"2023-03-02T16:57:43.394510060+00:00","thread":"chains-coordinator-0.0.0.0:20443","line":3814,"file":"src/chainstate/burn/db/sortdb.rs","apparent_sender":"1BVnHssMpsdJtuHsbcDQSL1gPNENNmSGcT"}
stacks-blockchain {"msg":"ACCEPTED(778995) leader block commit 636cbe92d2c9ce7cc4909008a0dffbc3bb4f3742d01ef854b1b5633fe5511d9f at 778995,341","level":"INFO","ts":"2023-03-02T16:57:43.397384840+00:00","thread":"chains-coordinator-0.0.0.0:20443","line":3814,"file":"src/chainstate/burn/db/sortdb.rs","apparent_sender":"1EyGWQu156JwYu7fnoMws2NzjAoBt8Lrzj"}
stacks-blockchain {"msg":"ACCEPTED(778995) leader block commit fab5ff89e2bfb895be61dcd52d8c99b75aad0a865addf6e55a23a24664642078 at 778995,442","level":"INFO","ts":"2023-03-02T16:57:43.401750506+00:00","thread":"chains-coordinator-0.0.0.0:20443","line":3814,"file":"src/chainstate/burn/db/sortdb.rs","apparent_sender":"1Gm3tiU3Rsm3pPpTnx3d3A54nug16TSWmZ"}
stacks-blockchain {"msg":"ACCEPTED(778995) leader block commit 5bdd3b9aa0ef92a7cd6ee5c6d49bc3a5540fec83e23165c166c6a31b1b4b4592 at 778995,849","level":"INFO","ts":"2023-03-02T16:57:43.405663376+00:00","thread":"chains-coordinator-0.0.0.0:20443","line":3814,"file":"src/chainstate/burn/db/sortdb.rs","apparent_sender":"1F6c8PicZVmxWQQV2Y2adeGvxSeFtewTDj"}
stacks-blockchain {"msg":"ACCEPTED(778995) leader block commit d34492fb9aa2e2515fc2f8878313215a66b09166076a6e8c7e4b637e7636c094 at 778995,850","level":"INFO","ts":"2023-03-02T16:57:43.411174707+00:00","thread":"chains-coordinator-0.0.0.0:20443","line":3814,"file":"src/chainstate/burn/db/sortdb.rs","apparent_sender":"1HyWJkJAJ8FmzpBiNPg5ToBsQAp3SCDazx"}
stacks-blockchain {"msg":"ACCEPTED(778995) leader block commit 6811daaa8a2a609087ae53bee735435854659823f966533617aad05d62896f6a at 778995,857","level":"INFO","ts":"2023-03-02T16:57:43.414524182+00:00","thread":"chains-coordinator-0.0.0.0:20443","line":3814,"file":"src/chainstate/burn/db/sortdb.rs","apparent_sender":"16gftbFvst7woWTXBXEPwJ2Spj39WWZctW"}
stacks-blockchain {"msg":"ACCEPTED(778995) leader block commit 79dbce68606d6cffba8ed7530593f83cde808041f2eb8612246a174a318a0d79 at 778995,858","level":"INFO","ts":"2023-03-02T16:57:43.420471407+00:00","thread":"chains-coordinator-0.0.0.0:20443","line":3814,"file":"src/chainstate/burn/db/sortdb.rs","apparent_sender":"13QWqXqhRPgNrGWNgaXmdZx6A2GRDjNbzg"}
stacks-blockchain {"msg":"ACCEPTED(778995) leader block commit ed776595cd029d8bc3dd9ccf19b5cd53fc0cc99c8d1e3273252287566f2f6bc9 at 778995,859","level":"INFO","ts":"2023-03-02T16:57:43.423041133+00:00","thread":"chains-coordinator-0.0.0.0:20443","line":3814,"file":"src/chainstate/burn/db/sortdb.rs","apparent_sender":"135YpZrtV4cdYgajtasVfhZqj51KCst4wt"}
stacks-blockchain {"msg":"Transaction rejected from mempool, {\"error\":\"transaction rejected\",\"reason\":\"NotEnoughFunds\",\"reason_data\":{\"actual\":\"0x00000000000000000000000000000000\",\"expected\":\"0x0000000000000000000000000000e740\"},\"txid\":\"01165541563847d049c473910dc3f7fb8a80f79a579c08df857b0b0b6255e83e\"}","level":"WARN","ts":"2023-03-02T16:57:44.281701105+00:00","thread":"relayer-http://0.0.0.0:20443","line":5178,"file":"src/net/p2p.rs"}
stacks-blockchain {"msg":"Transaction rejected from mempool, {\"error\":\"transaction rejected\",\"reason\":\"NotEnoughFunds\",\"reason_data\":{\"actual\":\"0x00000000000000000000000000000000\",\"expected\":\"0x00000000000000000000000000000802\"},\"txid\":\"347ce6cf79797e512c540abebaad83c4429bf83e98fe6d81ba59b65b6a985f74\"}","level":"WARN","ts":"2023-03-02T16:57:45.056803608+00:00","thread":"relayer-http://0.0.0.0:20443","line":5178,"file":"src/net/p2p.rs"}
stacks-blockchain {"msg":"Process abort due to thread panic: panicked at 'BUG: item is present in the bloom counter, but has a zero count (i = 9, slot = 11081)', src/util_lib/bloom.rs:537:17","level":"ERRO","ts":"2023-03-02T16:57:45.145508838+00:00","thread":"relayer-http://0.0.0.0:20443","line":58,"file":"testnet/stacks-node/src/main.rs"}
stacks-blockchain {"msg":"Panic backtrace:    0: stacks_node::main::{{closure}}\n             at src/testnet/stacks-node/src/main.rs:59:18\n   1: std::panicking::rust_panic_with_hook\n             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:588:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18\n   4: rust_begin_unwind\n             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5\n   5: core::panicking::panic_fmt\n             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14\n   6: blockstack_lib::util_lib::bloom::BloomCounter<H>::remove_raw\n   7: blockstack_lib::core::mempool::MemPoolTx::update_bloom_counter::{{closure}}\n             at src/src/core/mempool.rs:685:17\n      blockstack_lib::core::mempool::MemPoolTx::with_bloom_state\n             at src/src/core/mempool.rs:617:19\n      blockstack_lib::core::mempool::MemPoolTx::update_bloom_counter\n             at src/src/core/mempool.rs:682:9\n      blockstack_lib::core::mempool::MemPoolDB::try_add_tx\n             at src/src/core/mempool.rs:1869:9\n   8: blockstack_lib::core::mempool::MemPoolDB::tx_submit\n             at src/src/core/mempool.rs:2033:9\n   9: blockstack_lib::core::mempool::MemPoolDB::submit\n             at src/src/core/mempool.rs:2101:9\n  10: blockstack_lib::net::p2p::PeerNetwork::store_transaction\n             at src/src/net/p2p.rs:5169:25\n  11: blockstack_lib::net::p2p::PeerNetwork::store_transactions\n             at src/src/net/p2p.rs:5228:13\n  12: blockstack_lib::net::relay::Relayer::process_transactions\n             at src/src/net/relay.rs:1449:25\n      blockstack_lib::net::relay::Relayer::process_network_result\n             at src/src/net/relay.rs:1707:27\n  13: stacks_node::neon_node::RelayerThread::process_network_result::{{closure}}\n             at src/testnet/stacks-node/src/neon_node.rs:2025:13\n      stacks_node::neon_node::RelayerThread::with_chainstate\n             at src/testnet/stacks-node/src/neon_node.rs:1966:19\n      stacks_node::neon_node::RelayerThread::process_network_result\n             at src/testnet/stacks-node/src/neon_node.rs:2024:28\n      stacks_node::neon_node::RelayerThread::handle_directive\n             at src/testnet/stacks-node/src/neon_node.rs:3105:17\n  14: stacks_node::neon_node::StacksNode::relayer_main\n             at src/testnet/stacks-node/src/neon_node.rs:3773:17\n  15: stacks_node::neon_node::StacksNode::spawn::{{closure}}\n             at src/testnet/stacks-node/src/neon_node.rs:3903:17\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:122:18\n  16: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/mod.rs:514:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40\n      std::panicking::try\n             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19\n      std::panic::catch_unwind\n             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/mod.rs:513:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5\n  17: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys/unix/thread.rs:108:17\n","level":"ERRO","ts":"2023-03-02T16:57:45.249934392+00:00","thread":"relayer-http://0.0.0.0:20443","line":60,"file":"testnet/stacks-node/src/main.rs"}
stacks-blockchain Dumping core for pid 1
Stream closed EOF for mainnet-api-dr/mainnet-stacks-blockchain-archive-0 (stacks-blockchain)
```

### PR DESCRIPTION
**Pull request by jcnelson**
This fixes #3599.

The Stacks node uses a persistent bloom counter to sketch the recent contents of its mempool in a space-efficient way, which it uses to derive a bloom filter in order to query other nodes' mempools for transactions it does not have.  The bloom counter's `remove_raw()` method had been panicking in #3599 because it seemed that an item was simultaneously reported as present in the bloom counter and then turned out to be absent.

While this seems like a logic error (hence the original implementation's `panic!()` in this condition), it turns out this can happen naturally because an item can hash to the same bin multiple times.  If the bin has value _B_ and the item hashes to the same bin _C_ times, where _B < C_, then this panic condition arises.

The solution is to simply remove the panic.

### CODE REVIEW

File: src/util_lib/bloom.rs [hunk 1]
```diff
@@ -365,15 +365,15 @@ impl<H: BloomHash + Clone + StacksMessageCodec> BloomCounter<H> {
         let sql = format!("CREATE TABLE IF NOT EXISTS {}(counts BLOB NOT NULL, num_bins INTEGER NOT NULL, num_hashes INTEGER NOT NULL, hasher BLOB NOT NULL);", table_name);
         tx.execute(&sql, NO_PARAMS).map_err(db_error::SqliteError)?;
 
-        let (num_bits, num_hashes) = bloom_hash_count(error_rate, max_items);
-        let counts_vec = vec![0u8; (num_bits * 4) as usize];
+        let (num_bins, num_hashes) = bloom_hash_count(error_rate, max_items);
```
Comment (jcnelson) [inline src/util_lib/bloom.rs:368]: Note to the reviewer: this is just fixing a typo.

**Review by kantai — APPROVED** [review]

**Review by jo-tm — APPROVED** [review]
Removing panic if bin is empty, is not an abnormal condition.
