### PR TITLE
Fix/3227

### LINKED ISSUE #3227: P2P: Failed to process network dispatch: SendError
**Describe the bug**
A stacks-node (`2.05.0.2.2`) emitting events to a stacks-blockchain API (`4.0.3`) crashed at STX block `43233`, printing the following:
```
Process abort due to thread panic: panicked at 'explicit panic', testnet/stacks-node/src/neon_node.rs:779:29
Failed to write to fd: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
Failed to send data to socket TcpStream { addr: 172.25.26.7:59810, fd: 96 }: SendError("Failed to send 258 bytes")
http:id=236,request=true,peer=52.0.54.100:20443: failed to send on HTTP conversation: SendError("Failed to send 258 bytes")
P2P: Failed to process network dispatch: SendError("Failed to send 258 bytes")
Panic backtrace:    0: stacks_node::main::{{closure}}
             at src/testnet/stacks-node/src/main.rs:59:18
   1: std::panicking::rust_panic_with_hook
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:586:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   6: core::panicking::panic
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:48:5
   7: stacks_node::neon_node::spawn_peer::{{closure}}
             at src/testnet/stacks-node/src/neon_node.rs:779:29
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:122:18
   8: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/mod.rs:498:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
      std::panicking::try
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/mod.rs:497:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
   9: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys/unix/thread.rs:108:17
```

**Expected behavior**
I would've expected the stacks-node to retry the failed connection indefinitely instead of crashing.

**Environment (please complete the following information):**
`blockstack/stacks-blockchain:2.05.0.2.2` Docker image

### PR DESCRIPTION
**Pull request by jcnelson**
This fixes #3227 by making all of the `PeerNetwork::do_network_dispatch()`-invoked sub-state-machines infallible.  They now absorb all of their errors and handle them by simply resetting (which is what would happen anyway).  No longer will their errors be propagated up to `PeerNetwork::run()`.

Now, the only way `PeerNetwork::run()` can fail is if it was not bound to a port, in which case the caller should `panic!()` because the code itself is buggy.

### CODE REVIEW

File: src/net/inv.rs [hunk 1]
```diff
@@ -2249,7 +2249,7 @@ impl PeerNetwork {
         &mut self,
         sortdb: &SortitionDB,
         ibd: bool,
-    ) -> Result<(bool, bool, Vec<NeighborKey>, Vec<NeighborKey>), net_error> {
+    ) -> (bool, bool, Vec<NeighborKey>, Vec<NeighborKey>) {
         PeerNetwork::with_inv_state(self, |network, inv_state| {
```
Comment (kantai) [inline src/net/inv.rs:2253]: Is there any path in this anonymous function that returns `Err`? I'd be more comfortable with the `expect()` at the end of this call if `with_inv_state`'s signature looked more like:

```
    pub fn with_inv_state<F, R>(network: &mut PeerNetwork, handler: F) -> Result<R, net_error>
    where
        F: FnOnce(&mut PeerNetwork, &mut InvState) -> R,
```

That way, the `.expect()` is explicitly only unwrapping a failure in the outer method (so, it's just a failure in opening the inv state).

Comment (jcnelson) [reply src/net/inv.rs:2253]: Sure, changed it to that signature and refactored the needful.

**Review by kantai — APPROVED** [review]
LGTM -- can you add a line to the changelog as well?

**Review by gregorycoppola — APPROVED** [review]
I would consider not removing all of the `Result` plumbing.

You never know when you might want to use it again.

But, just an optional idea.
