### PR TITLE
fix: incrementally vacuum the MARF DB when migrating

### LINKED ISSUE #3121: Manage disk space in MARF sqlite blobs -> external file migration
The current MARF sqlite blobs to external file migration code effectively doubles the space usage of the MARF. This isn't for lack of trying, though. In `inner_write_external_trie_blob` (in `trie_sql.rs`):

```rust
        let empty_blob: &[u8] = &[];
        let args: &[&dyn ToSql] = &[
            block_hash,
            &empty_blob,
            &0,
            &u64_to_sql(offset)?,
            &u64_to_sql(length)?,
            &block_id,
        ];
        let mut s =
            conn.prepare("UPDATE marf_data SET block_hash = ?1, data = ?2, unconfirmed = ?3, external_offset = ?4, external_length = ?5 WHERE block_id = ?6")?;
        s.execute(args)?;
```

The data blobs get zeroed. _However_ SQLite won't actually remove the blob data from the db file: it just fills it with zeroes (in almost all cases). This means that the migration currently inflates the MARF storage by ~2x. Performing periodic [vacuums](https://www.sqlite.org/lang_vacuum.html) during the migration would help eliminate this issue.

Note: in Hiro's testing of the migration, running out of disk space caused crashes during migration (which corrupted the chain state).

### PR DESCRIPTION
**Pull request by jcnelson**
This fixes #3121 by making it so the MARF migration code to move trie blobs to a .blobs file will vacuum the DB periodically during the migration (i.e. every 4096 blocks).  I've confirmed this works on a live setting -- the database file now shrinks over the course of the migration.

### CODE REVIEW

**Comment by jcnelson** [comment]
One TODO item on this PR is to also set the `SQLITE_TMPDIR` pragma on the connection so that the temporary vacuum file will be created in the _same directory_ as the database file.  Otherwise, if the user keeps their chain state on a separate disk (which we do at the Foundation) will get an unexpected "disk full" failure followed by a runtime panic.

**Comment by jcnelson** [comment]
* Highlight this in the changelog -- you'll need 2x the space required to migrate

* You can't recover (yet) from a failed migration

* Add a sanity check to restart a failed migration (or abort)

* Only vacuum once

File: src/chainstate/stacks/index/file.rs [hunk 1]
```diff
@@ -191,14 +192,42 @@ impl TrieFile {
...
             "Migrate {} blocks to external blob storage at {}",
             max_block,
             &self.get_path()
         );
+
+        // vacuum the DB every so often when running this, since the DB file won't shrink
+        // otherwise.
+        let vacuum_frequency = 1024;
+
+        // set SQLITE_TMPDIR if it isn't set ailready
```
Comment (pavitthrap) [inline src/chainstate/stacks/index/file.rs:213]: s/ailready/already

**Review by pavitthrap — APPROVED** [review]
